services:
  postgres:
    image: postgres:16
    container_name: finance-postgres
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: abc
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  finance-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finance_db
      SPRING_DATASOURCE_USERNAME: finance_user
      SPRING_DATASOURCE_PASSWORD: abc
    stdin_open: true
    tty: true

volumes:
  pg_data: