spring.application.name=Finance-Manager-Api

spring.datasource.url=jdbc:postgresql://postgres:5432/finance_db
spring.datasource.username=finance_user
spring.datasource.password=abc
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect







